# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_equipments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request_for_state_admin',
            old_name='age',
            new_name='agex',
        ),
    ]
