# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 06:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medical_equipments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=20, verbose_name='Email ID')),
                ('mobile', models.CharField(max_length=10, verbose_name='Mobile number')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Middle name')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='state_adminregister',
            name='email',
            field=models.EmailField(max_length=100, unique=True, verbose_name='Email ID'),
        ),
        migrations.AlterUniqueTogether(
            name='state_adminregister',
            unique_together=set([]),
        ),
    ]
