# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 09:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_equipments', '0003_auto_20160601_1217'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='state_adminregister',
            new_name='request_for_state_admin',
        ),
    ]
