# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_equipments', '0005_auto_20160607_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='id_available',
            new_name='equipment_id_available',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='is_warranty',
            new_name='equipment_in_warranty',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='under_amc',
            new_name='equipment_under_AMC_CMC',
        ),
        migrations.AddField(
            model_name='hospital',
            name='country',
            field=models.CharField(default='India', max_length=100, verbose_name='Country'),
            preserve_default=False,
        ),
    ]
