# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_equipments', '0006_auto_20160607_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='hospital_id_available',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='Yes', max_length=3, verbose_name='Hospital ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='hpspital_type_2',
            field=models.CharField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary'), ('Tertiary', 'Tertiary')], default='Tertiary', max_length=20, verbose_name='Hospital Type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipment',
            name='warranty_expiry',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Warranty Expiry Date'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hospital_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Enter Hospital ID'),
        ),
    ]
