# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical_equipments', '0007_auto_20160602_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso2_code', models.CharField(max_length=2, unique=True, verbose_name='ISO alpha-2')),
                ('name', models.CharField(max_length=128, verbose_name='Official name (CAPS)')),
                ('printable_name', models.CharField(max_length=128, verbose_name='Country name')),
                ('iso3_code', models.CharField(max_length=3, unique=True, verbose_name='ISO alpha-3')),
                ('numcode', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ISO numeric')),
                ('continent', models.CharField(choices=[('AF', 'Africa'), ('NA', 'North America'), ('EU', 'Europe'), ('AS', 'Asia'), ('OC', 'Oceania'), ('SA', 'South America'), ('AN', 'Antarctica')], max_length=2, verbose_name='Continent')),
                ('active', models.BooleanField(default=True, verbose_name='Country is active')),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ('name',),
                'verbose_name': 'Country',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='State/Province name')),
                ('abbr', models.CharField(blank=True, max_length=3, null=True, verbose_name='State/Province Abbreviation')),
                ('active', models.BooleanField(default=True, verbose_name='State/Province is active')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_equipments.Country')),
            ],
            options={
                'verbose_name_plural': 'States/Provinces',
                'ordering': ('name',),
                'verbose_name': 'State/Province',
            },
        ),
    ]
