# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 09:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_equipments', '0007_auto_20160608_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='hpspital_type_2',
            new_name='hpspital_type_b',
        ),
    ]
