# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 10:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_equipments', '0009_auto_20160608_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='hpspital_cat',
            new_name='hospital_cat',
        ),
    ]
