# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_equipments', '0010_auto_20160602_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_id', models.CharField(max_length=100, verbose_name='Hospital ID')),
                ('hospital_name', models.CharField(max_length=250, verbose_name='Hospital Name')),
                ('hospital_type', models.CharField(choices=[('Government', 'Government'), ('Private', 'Private')], max_length=50, verbose_name='Category')),
                ('email', models.EmailField(max_length=100, verbose_name='Email ID')),
                ('mobile', models.CharField(max_length=10, verbose_name='Mobile Number')),
                ('address', models.CharField(max_length=600, verbose_name='Address')),
            ],
        ),
    ]
