# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_equipments', '0011_auto_20160609_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Equipment ID'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_id_available',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=3, verbose_name='Equipment ID Available'),
        ),
    ]
