# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_equipments', '0012_auto_20160609_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='installation_date',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Date of Installation'),
        ),
    ]
