# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_equipments', '0012_auto_20160603_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_id', models.CharField(max_length=100, verbose_name='Hospital ID')),
                ('equipment_id', models.CharField(max_length=100, verbose_name='Equipment ID')),
                ('hospital_name', models.CharField(max_length=250, verbose_name='Hospital Name')),
                ('state', models.CharField(max_length=30, verbose_name='State')),
                ('district', models.CharField(max_length=100, verbose_name='District')),
                ('signed', models.CharField(max_length=100, verbose_name='Updated By')),
            ],
        ),
        migrations.DeleteModel(
            name='userpost',
        ),
    ]
