# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_equipments', '0013_auto_20160603_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='change_password',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_password', models.CharField(max_length=100, verbose_name='Old Password')),
                ('new_password1', models.CharField(max_length=100, verbose_name='New Password')),
                ('new_password2', models.CharField(max_length=250, verbose_name='Confirm New Password')),
            ],
        ),
    ]
