# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 07:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('medical_equipments', '0013_auto_20160610_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 10, 7, 1, 35, 170762, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 10, 7, 1, 53, 275239, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
