# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 05:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_equipments', '0014_change_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='change_password',
        ),
    ]
